### ISSUE TITLE
Blender versions beyond 2.92?

### ISSUE THREAD

**Issue by jpvivere** [LogicReinc/LogicReinc.BlendFarm#10]
Thank you for this program! I tried to hack VersionCache to add Blender 2.93.4 by copying the 2.92 data, then copied this to a server also. BlendFarm accepts the 2.93.4 selection, but always re-downloads 2.93.4 on the server (even though it's already there from previous BlendFarm downloading), and then fails rendering due to version mismatch. Any hints on adding later Blender versions, or is this known to not work?

**Comment by LogicReinc** [comment]
Hey jpvivere,

BlendFarm should automatically be able to fetch new versions as they become available. Simply deleting the VersionCache on all machines and restarting BlendFarm should force BlendFarm to update its VersionCache including new versions of Blender.

After that it should download the appropriate version as expected. Note that if you dont delete it on other machines it may fail to find the version.
Normally, VersionCache is invalidated every 3 days I believe, but if you never restart Blendfarm, it never gets invalidated.

If this solves the issue lemme know. Otherwise ill do some more investigating. 
I plan on releasing a new version of BlendFarm likely next month if my time allows, so if its a bug I may incorporate the fix there.

**Comment by LogicReinc** [comment]
To provide some clear steps I suggest:
 - Stop BlendFarm
 - Delete the downloaded (or copied) version 2.93.4 from all machines
 - Delete VersionCache on all machines
 - Start BlendFarm (Client/Server) on machines

Now 2.93.4 should be visible on your client, and it should download the correct version on every machine without version mismatches.

**Comment by jpvivere** [comment]
Thanks for the response. I tried it again, and got the same result.

The best I can tell, it's [this line](https://github.com/LogicReinc/LogicReinc.BlendFarm/blob/101ceb2826aecf60cb40c310850401a40e83eb10/LogicReinc.BlendFarm.Shared/BlenderVersion.cs#L96) that's keeping the program from adding specific versions to the cache list because while filtering the available Blender versions, in [the 2.93 directory](https://download.blender.org/release/Blender2.93/) (and in other places), Blender has added MSIX and/or macos-arm64 installer options, and this code assumes valid installs are exactly 4 options (tar.xz, dmg, msi, zip).

This is not a priority for me, so no hurry, and thanks again for making this program!

**Comment by LogicReinc** [comment]
hey jpvivere,

Good catch, This indeed seems to be the case.
I shall fix this in the upcoming build so that it no longer cares about how many, but which are available instead.

If you need it badly, you can use the custom blender build functionality to manually add 2.93 as a version (with a custom name).
There is a button on the initial window to add a custom version, this walks you through the process.
Such a custom version will not interfere with the official versions and thus shouldnt cause these conflicts.
(It obviously will require you to do this manually on every machine)
Hopefully that helps you out in the short term.
