### ISSUE TITLE
Blender 3.0: RenderSettings object has no attribute 'tile_x'

### ISSUE THREAD

**Issue by j-garza** [LogicReinc/LogicReinc.BlendFarm#15]
I could be wrong but it looks like blender 3 won't be compatible with current BlendFarm :( 

https://docs.blender.org/api/3.0/bpy.types.RenderSettings.html
https://wiki.blender.org/wiki/Process/Release_Cycle

> The Python API remains stable during this phase [beta]

**Comment by LogicReinc** [comment]
If this will cause an issue I will take a look on how to approach it in Blender 3.0. 
I'm quite busy atm and since Blender 3.0 isn't officially released yet I haven't looked at it in detail yet.

I can't imagine them outright removing the functionality entirely and I'm sure there is an alternative.
(At a quick glance it appears they simply renamed it to border_min_x etc I assume)

**Comment by megabitsenmzq** [comment]
Blender 3.0 is released! I'm looking forward to the update of BlendFarm 😊.

**Comment by LogicReinc** [comment]
Alright, Hopefully I can get the fix out upcoming week

**Comment by LogicReinc** [comment]
Resolved in version 1.0.8 which just released, enjoy.
