### ISSUE TITLE
Render fail: Cannot access a disposed object

### ISSUE THREAD

**Issue by dreamparacite** [LogicReinc/LogicReinc.BlendFarm#38]
![render_error](https://user-images.githubusercontent.com/1375891/171210080-d014f7c5-9e91-41dd-9381-947f44a854ad.png)

Hello, I've been enjoying using BlendFarm for the past few weeks, however I'm noticing two of my computers pretty consistently end up failing during a render with the error: "Render fail: Cannot access a disposed object. Object name: 'System.Net.Sockets.TcpClient'. Both computers are using Windows 10 and ethernet. Attached is a screenshot of the GUI client and a screenshot of the command prompt from one of the computers that failed.

**Comment by LogicReinc** [comment]
At a glance it looks like the connection gets closed (aka loses connection).
Especially since its the same 2 computers, I assume they have an unstable ethernet connection. (Bad cable? Router?)

Reconnection is planned at some point, but is currently a low priority issue. (#18 )

If there is any more info available let me know, it is clearly the connection getting closed, but the reason is not clear.
Is there any error on the render node console?

**Comment by LogicReinc** [comment]
@dreamparacite Basic reconnection was implemented in v1.1.3, this might fix this issue, but as the root cause wasn't entirely clear its not 100% certain it fixes it. Consistent failure may also ruin performance, as the render node does need to restart.
