### ISSUE TITLE
Multi GPU support on Windows 11

### ISSUE THREAD

**Issue by DrCard** [LogicReinc/LogicReinc.BlendFarm#59]
I' installed 3 GPU on my windows 11 work station
but its only using 1 GPU  I couldn't get the 3 to work at the same time 

![Screenshot_20230128_051725](https://user-images.githubusercontent.com/5873756/215268777-a196c0b1-66b5-42b1-8c60-89b2464cea65.png)
![Screenshot_20230128_051814](https://user-images.githubusercontent.com/5873756/215268779-689f7e46-5e21-4f51-ac76-074d4ed1dd41.png)

**Comment by LogicReinc** [comment]
Hey @DrCard 
One thing to keep in mind is that the graphs you see there are not Blender activity. To see Blender activity, you need to change one of the graphs to "CUDA", you do not see utilization otherwise.

If I look at your logs, we can see it does enable all your GPUs (the 1 after the GPU indicates that its enabled for rendering, and in this case you see your intel cpu is disabled with a 0).

I recommend first changing the graphs to CUDA, and then verify if its still not using all of them.

If it is REALLY not using all of them, then it might be a bug. Let me know.

**Comment by acollaborator** [comment]
Multi GPU support on Windows 11 works.

I installed 3 GTX 1060 GPUs on a Windows system running BlendFarm.Server  and set a RenderType pf OPTIX_GPUONLY using the gear icon for the corresponding Render Node in the BlenFarm client interface.

I confirmed all GPUs were utilized using a performance monitoring utility called HWiNFO .
