### ISSUE TITLE
Image wont show up

### ISSUE THREAD

**Issue by Lynchon83** [LogicReinc/LogicReinc.BlendFarm#6]
Hi, I'm testing this awesome piece of software on a big scene (1.3gb) as everything worked fine with the default cube.

The problem is that even if everything seems to work fine (sync works, render loads and starts...) the final rendered image won't show anywhere. Is there any check I should do to be sure the blend file is correct? as I said the .blend is quite big and there are thousands of things that might be affecting.

Thank you.

**Comment by LogicReinc** [comment]
Hmm, hard to say. If you say render loads, it starts.
I assume when you start the render (also using the Local render node) you can see Blender rendering in the console?
Does it show anything interesting in particular?
Generally, if Blender can render it, so should BlendFarm, BlendFarm still uses normal Blender to render it.
Do you use special addons that are required to be active during rendering? (As BlendFarm runs Blender instances as a factory instance unaffected by these things).
Obviously the easiest way to find the issue would be for me to receive the .blendfile somehow.
So if you have any more information that would be great.

**Comment by LogicReinc** [comment]
Also, if a render does succeed but for whatever reason it is an UI issue, there should appear a lastRender.png in the application directory. (Same directoy as executable, or for MacOS in Application Support/BlendFarm)

**Comment by Lynchon83** [comment]
Im not using the local render node, but console on the other render nodes seem to run with no issues, I'm attaching a screenshot of one the nodes when render finishes.

![Captura de pantalla 2021-05-12 114812](https://user-images.githubusercontent.com/45634961/117958257-228bac80-b31b-11eb-93d6-a23a7b14f2d7.png)


I'm sorry but I'm not allowed to share the blend file. Here is also the crash.txt that shows up when I try to use the local render node.

[66251596-2a8e-40db-8c00-dd6830f105e3.crash.txt](https://github.com/LogicReinc/LogicReinc.BlendFarm/files/6465419/66251596-2a8e-40db-8c00-dd6830f105e3.crash.txt)

**Comment by Lynchon83** [comment]
I've noticed that the image is created once the render is done inside the Blendfarm folder, but is an empty png

**Comment by LogicReinc** [comment]
Yea I understand you may not be able to share it. However if you do manage to create a simple file without proprietary assets that would be great.

Some things you can try:
 - Switch RenderStrategy to ChunkedSplitted, And do a render this way. It will likely crash, after the first chunk is rendered. After this, check the RenderData directory on the render node, see if there is a png for that chunk (the ID will be listed as you see in your own screenshot). See if that image has anything rendered in it.

 - Try disabling any compositing in your Blendfile and see if that allows it to render.

 - Try rendering the file using Blender directly using the command line and see if this works using the command: blender -b yourBlendFile.blend -b -o someOutputPath.png -f 1
   (Assuming you're on windows, you can copy the blendfile in your blender installation directory so you have access to the blender executable that way)

 - By default, BlendFarm renders frame 0, Maybe nothing exists at t=0? You can change this by going to the animation tab and changing Frame Start to 1 or more, then render in the Image tab. (This frame is also used for individual renders in the Image tab)

If any of these works, do tell me which so I know this for future reference. If none of this works, I suggest maybe you can reduce the file, deleting assets that you cant share. So that I can test and try to solve it here locally.

Hopefully any of this helps, Good Luck.

**Comment by LogicReinc** [comment]
Also, try manually copying the file to the RenderNode and try rendering it using Blender there, see if it crashes there without using BlendFarm. (You can use the installations provided by BlendFarm in the /BlenderData directories )

**Comment by Lynchon83** [comment]
My bad, I did try the two points you suggested (deleting composition and checking frames) but I'm almost completely sure it had to do with my view layer configuration, I had some view layers not enabled for rendering, so I'm not sure what solved the issue but I can confirm it works perfectly now.

Thanks again.

Looking forward for new releases :)

**Comment by LogicReinc** [comment]
Glad to see it wasn't an issue with the system.
New release with denoiser override option hopefully today if my time allows.

Good luck and enjoy the software.
