### ISSUE TITLE
Server provides the recommended renderer settings to the client

### ISSUE THREAD

**Issue by eigeen** [LogicReinc/LogicReinc.BlendFarm#63]
In the current version, the client sets the render and denoise mode of the node to CPU by default.

It might be better if the server provides the server's preset best settings (such as OPTIX) when connecting.

**Comment by LogicReinc** [comment]
You only have to configure your nodes once, if you save it, it will use those same settings the next time.
The client is not actually aware of any of your hardware capabilities. 
Choosing for example OPTIX is not necessarily always the most logical choice depending on your systems (eg. older gpus or mixed-gpu environment).
 
The only option that comes to mind is forcing users to select which rendertype to use whenever you add a node for the first time, but this would not really make it less work necessarily. Just simpler for new users.

Perhaps I misread your suggestion, but at the moment you only configure your nodes once, and never have to do it again unless you:
 - Change client pc
 - Delete the config files
 - Reinstall BlendFarm

Denoiser mode by default uses whatever you set in your blendfile. Since denoising is often a project-specific setting.

If you have more context about your environment perhaps I can better understand your usecase

**Comment by eigeen** [comment]
> You only have to configure your nodes once, if you save it, it will use those same settings the next time. The client is not actually aware of any of your hardware capabilities. Choosing for example OPTIX is not necessarily always the most logical choice depending on your systems (eg. older gpus or mixed-gpu environment).
> 
> The only option that comes to mind is forcing users to select which rendertype to use whenever you add a node for the first time, but this would not really make it less work necessarily. Just simpler for new users.
> 
> Perhaps I misread your suggestion, but at the moment you only configure your nodes once, and never have to do it again unless you:
> 
> * Change client pc
> * Delete the config files
> * Reinstall BlendFarm
> 
> Denoiser mode by default uses whatever you set in your blendfile. Since denoising is often a project-specific setting.
> 
> If you have more context about your environment perhaps I can better understand your usecase

The reason for this suggestion is that I tried to share this tool with a friend before, but he neglected to modify the renderer function when he added the server for the first time, resulting in CPU rendering, which was inefficient.

And you're right, maybe adding servers that require you to change the render type might be a good option.
